### ISSUE TITLE
タンクrotate問題 in tanks branch

### ISSUE THREAD

**Issue by saityyy** [kajikentaro/ML-tanks#1]
タンクの砲台が不適切な軸を中心に回転してしまう
@saityyy 
@auaua159

**Comment by auaua159** [comment]
とりあえず回転とか無視します。
タンク諸々作るけど斎藤どうする？

**Comment by saityyy** [comment]
とりあえず弾丸と壁をblenderで軽く作る。
それのモデリングができたら
@saityyy 弾丸当たり判定
@kajikentaro ステージ（壁の配置）の形成に取り掛かる。
それまでに戦車の挙動をある程度確立しておいてほしい。
これらが終わったら統合作業に入る。
